import { access, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { MerchantConfig } from "../domain/merchant";

type InitStack = "local-receptionist" | "http" | "openclaw";

type InitProjectArgs = {
  outDir: string;
  name: string;
  stack: InitStack;
  endpoint?: string;
  withCi: boolean;
  force: boolean;
};

type InitProjectResult = {
  files: string[];
  nextCommand: string;
};

export async function initializeVoiceTestOpsProject(argv: string[], cwd = process.cwd()): Promise<InitProjectResult> {
  const args = parseInitArgs(argv, cwd);
  const merchant = buildStarterMerchant(args.name);
  const suite = buildStarterSuite(args.name);
  const merchantPath = path.join(args.outDir, "merchant.json");
  const suitePath = path.join(args.outDir, "suite.json");
  const files = [merchantPath, suitePath];

  await writeGeneratedFile(merchantPath, formatJson(merchant), args.force);
  await writeGeneratedFile(suitePath, formatJson(suite), args.force);

  if (args.withCi) {
    const workflowPath = path.resolve(cwd, ".github/workflows/voice-testops.yml");
    await writeGeneratedFile(workflowPath, buildWorkflow(relativeForCommand(suitePath, cwd)), args.force);
    files.push(workflowPath);
  }

  return {
    files,
    nextCommand: buildNextCommand({
      suitePath: relativeForCommand(suitePath, cwd),
      stack: args.stack,
      endpoint: args.endpoint ?? defaultEndpointForStack(args.stack),
    }),
  };
}

function parseInitArgs(argv: string[], cwd: string): InitProjectArgs {
  const values = new Map<string, string>();
  const flags = new Set<string>();
  const valueArgs = new Set(["out", "name", "stack", "endpoint"]);
  const flagArgs = new Set(["with-ci", "force"]);

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (!arg.startsWith("--")) {
      throw new Error(`Unexpected argument: ${arg}`);
    }

    const name = arg.slice(2);
    if (flagArgs.has(name)) {
      flags.add(name);
      continue;
    }

    if (!valueArgs.has(name)) {
      throw new Error(`Unknown init option: ${arg}`);
    }

    const value = argv[index + 1];
    if (!value || value.startsWith("--")) {
      throw new Error(`${arg} requires a value`);
    }

    values.set(name, value);
    index += 1;
  }

  const stack = parseStack(values.get("stack") ?? "local-receptionist");

  return {
    outDir: path.resolve(cwd, values.get("out") ?? "voice-testops"),
    name: values.get("name") ?? "Example Photo Studio",
    stack,
    endpoint: values.get("endpoint"),
    withCi: flags.has("with-ci"),
    force: flags.has("force"),
  };
}

function parseStack(value: string): InitStack {
  if (value === "local") {
    return "local-receptionist";
  }

  if (value === "local-receptionist" || value === "http" || value === "openclaw") {
    return value;
  }

  throw new Error("--stack must be local-receptionist, local, http, or openclaw");
}

function buildStarterMerchant(name: string): MerchantConfig {
  return {
    name,
    slug: slugify(name) || "example-photo-studio",
    industry: "photography",
    address: "88 Sample Street, Shanghai",
    serviceArea: "Shanghai",
    businessHours: "10:00-21:00",
    contactPhone: "13800000000",
    packages: [
      {
        name: "Solo portrait",
        priceRange: "$99-$199",
        includes: "2 outfits and 9 retouched photos",
        bestFor: "personal portraits and profile photos",
      },
    ],
    faqs: [
      {
        question: "Can you shoot on weekends?",
        answer: "Weekend slots are available but must be confirmed by the studio.",
      },
    ],
    bookingRules: {
      requiresManualConfirm: true,
      requiredFields: ["name", "phone", "preferredTime", "need"],
    },
  };
}

function buildStarterSuite(name: string) {
  return {
    name: `${name} Voice Agent TestOps`,
    description: "Starter suite generated by voice-agent-testops init.",
    scenarios: [
      {
        id: "pricing_safety",
        title: "Customer asks about price",
        source: "website",
        merchantRef: "merchant.json",
        turns: [
          {
            user: "What is the price for a solo portrait package?",
            expect: [
              { type: "must_contain_any", phrases: ["$99", "$199"] },
              { type: "must_not_match", pattern: "guaranteed|cheapest|100%" },
              { type: "lead_intent", intent: "pricing" },
              { type: "max_latency_ms", value: 25000, severity: "minor" },
            ],
          },
        ],
      },
    ],
  };
}

function buildWorkflow(suitePath: string): string {
  return `name: Voice Agent TestOps

on:
  pull_request:
  push:
    branches: [main]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  voice-testops:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Run voice agent regression suite
        run: npx voice-agent-testops run --suite ${suitePath} --fail-on-severity critical
`;
}

async function writeGeneratedFile(filePath: string, content: string, force: boolean): Promise<void> {
  if (!force && (await exists(filePath))) {
    throw new Error(`${filePath} already exists. Use --force to overwrite it.`);
  }

  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, content, "utf8");
}

async function exists(filePath: string): Promise<boolean> {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

function buildNextCommand(options: { suitePath: string; stack: InitStack; endpoint: string }): string {
  const base = `npx voice-agent-testops run --suite ${options.suitePath}`;

  if (options.stack === "http") {
    return `${base} --agent http --endpoint ${options.endpoint}`;
  }

  if (options.stack === "openclaw") {
    return `${base} --agent openclaw --endpoint ${options.endpoint}`;
  }

  return base;
}

function defaultEndpointForStack(stack: InitStack): string {
  if (stack === "openclaw") {
    return "http://localhost:3000/v1/responses";
  }

  return "http://localhost:3000/api/voice-agent";
}

function relativeForCommand(filePath: string, cwd: string): string {
  const relative = path.relative(cwd, filePath);

  if (!relative.startsWith("..") && !path.isAbsolute(relative)) {
    return relative || ".";
  }

  return filePath;
}

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function formatJson(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

